language: python
python:
  - "3.7"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then travis_retry pip install -r requirements.txt; fi
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - cp tcrdist/datasets/dash.csv dash.csv
  - mkdir static
  - mkdir static3
  - python -c "import tcrregex as td; td.setup_db.install_all_next_gen()"
  - python -c "import tcrregex as td; td.install_test_files.install_test_files()"
  - pytest --cov=tcrdist/
after_success:
  - coveralls
